import { Bounty } from "./types";

const baseReq = {
  minPhotos: 3,
  mustIncludePlate: true,
  mustIncludeLocation: true,
  mustBeMoving: false,
};

export const bounties: Bounty[] = [
  // ── Tier 1 · Street (0.25 + 0.35 + 0.5 + 0.75 = 1.85 SOL) ──
  {
    id: "t1-1",
    title: "Dodge Challenger Hellcat — Detroit",
    description:
      "Hellcat Widebody in Sublime or F8 Green. Muscle car meet spots count.",
    make: "Dodge",
    model: "Challenger Hellcat",
    yearRange: "2019-2026",
    category: "muscle",
    rarity: "common",
    tier: 1,
    reward: 0.25,
    location: "Detroit, MI",
    radiusMiles: 35,
    status: "open",
    postedBy: "muscle_mike",
    postedByAvatar: "MK",
    postedAt: "2026-06-08T20:00:00Z",
    expiresAt: "2026-06-18T23:59:00Z",
    submissions: 18,
    views: 340,
    requirements: { ...baseReq, minPhotos: 2 },
    tags: ["dodge", "hellcat", "muscle"],
    imageUrl: "/cars/b9.jpg",
  },
  {
    id: "t1-2",
    title: "Toyota Supra MK4 Turbo — Atlanta",
    description:
      "Stock or lightly modified MK4 Supra Turbo. 6-speed manual preferred. No replica builds.",
    make: "Toyota",
    model: "Supra MK4",
    yearRange: "1993-1998",
    category: "jdm",
    rarity: "uncommon",
    tier: 1,
    reward: 0.35,
    location: "Atlanta, GA",
    radiusMiles: 40,
    status: "open",
    postedBy: "2jz_lover",
    postedByAvatar: "2J",
    postedAt: "2026-06-08T16:45:00Z",
    expiresAt: "2026-06-22T23:59:00Z",
    submissions: 5,
    views: 620,
    requirements: baseReq,
    tags: ["supra", "mk4", "jdm"],
    imageUrl: "/cars/b7.jpg",
  },
  {
    id: "t1-3",
    title: "Porsche 911 GT3 RS 992 — NYC Metro",
    description:
      "992-gen GT3 RS in Weissach pack preferred. Manhattan, Brooklyn, or Jersey City area.",
    make: "Porsche",
    model: "911 GT3 RS",
    yearRange: "2023-2026",
    color: "Python Green",
    category: "supercar",
    rarity: "rare",
    tier: 1,
    reward: 0.5,
    location: "New York, NY",
    radiusMiles: 25,
    status: "open",
    postedBy: "zuffenhausen_fan",
    postedByAvatar: "ZF",
    postedAt: "2026-06-08T11:30:00Z",
    expiresAt: "2026-06-15T23:59:00Z",
    submissions: 12,
    views: 890,
    requirements: { ...baseReq, minPhotos: 2 },
    tags: ["porsche", "gt3rs", "992"],
    imageUrl: "/cars/b4.jpg",
  },
  {
    id: "t1-4",
    title: "Ford Mustang Shelby GT500 — Dallas",
    description:
      "S550 Shelby GT500 in the wild around DFW. Carbon track pack bonus.",
    make: "Ford",
    model: "Mustang Shelby GT500",
    yearRange: "2020-2026",
    category: "muscle",
    rarity: "uncommon",
    tier: 1,
    reward: 0.75,
    location: "Dallas, TX",
    radiusMiles: 30,
    status: "open",
    postedBy: "texas_muscle",
    postedByAvatar: "TM",
    postedAt: "2026-06-07T10:00:00Z",
    expiresAt: "2026-06-21T23:59:00Z",
    submissions: 9,
    views: 510,
    requirements: baseReq,
    tags: ["ford", "mustang", "shelby"],
    imageUrl: "/cars/b9.jpg",
  },

  // ── Tier 2 · Sport (1 + 1.25 + 1.5 + 2 = 5.75 SOL) ──
  {
    id: "t2-1",
    title: "R34 GT-R V-Spec II — Los Angeles",
    description:
      "Verified R34 Skyline GT-R V-Spec II in the wild around LA. Must show V-Spec badge.",
    make: "Nissan",
    model: "Skyline GT-R R34",
    yearRange: "1999-2002",
    color: "Bayside Blue",
    category: "jdm",
    rarity: "legendary",
    tier: 2,
    reward: 1,
    location: "Los Angeles, CA",
    radiusMiles: 50,
    status: "open",
    postedBy: "jdm_archive",
    postedByAvatar: "JA",
    postedAt: "2026-06-06T09:15:00Z",
    expiresAt: "2026-06-20T23:59:00Z",
    submissions: 7,
    views: 3201,
    requirements: { ...baseReq, minPhotos: 4 },
    tags: ["r34", "gtr", "jdm"],
    imageUrl: "/cars/b2.jpg",
  },
  {
    id: "t2-2",
    title: "Pagani Huayra BC — Miami Beach",
    description:
      "Pagani Huayra BC spotted in Miami-Dade. Clear exterior shot showing the full car.",
    make: "Pagani",
    model: "Huayra BC",
    yearRange: "2016-2019",
    color: "Blue Carbon",
    category: "hypercar",
    rarity: "unicorn",
    tier: 2,
    reward: 1.25,
    location: "Miami, FL",
    radiusMiles: 30,
    status: "open",
    postedBy: "exotic_collector",
    postedByAvatar: "EC",
    postedAt: "2026-06-07T14:22:00Z",
    expiresAt: "2026-06-21T23:59:00Z",
    submissions: 3,
    views: 1842,
    requirements: {
      ...baseReq,
      mustIncludePlate: false,
      notes: "Exterior shots only. No dealership inventory.",
    },
    tags: ["pagani", "hypercar", "miami"],
    imageUrl: "/cars/b1.jpg",
  },
  {
    id: "t2-3",
    title: "Lamborghini Countach LP400 — Beverly Hills",
    description:
      "Original LP400 Periscopio Countach. Periscopio roof mirror required in photos.",
    make: "Lamborghini",
    model: "Countach LP400",
    yearRange: "1974-1978",
    category: "classic",
    rarity: "legendary",
    tier: 2,
    reward: 1.5,
    location: "Beverly Hills, CA",
    radiusMiles: 15,
    status: "open",
    postedBy: "wedge_hunter",
    postedByAvatar: "WH",
    postedAt: "2026-06-01T08:00:00Z",
    expiresAt: "2026-06-14T23:59:00Z",
    submissions: 2,
    views: 4100,
    requirements: { ...baseReq, mustIncludePlate: false },
    tags: ["countach", "lamborghini", "classic"],
    imageUrl: "/cars/b5.jpg",
  },
  {
    id: "t2-4",
    title: "Audi R8 V10 Performance — Chicago",
    description:
      "R8 V10 Performance coupe or spyder. Must be on public roads, not at a dealer.",
    make: "Audi",
    model: "R8 V10 Performance",
    yearRange: "2020-2026",
    category: "supercar",
    rarity: "rare",
    tier: 2,
    reward: 2,
    location: "Chicago, IL",
    radiusMiles: 25,
    status: "open",
    postedBy: "midwest_exotics",
    postedByAvatar: "ME",
    postedAt: "2026-06-05T12:00:00Z",
    expiresAt: "2026-06-25T23:59:00Z",
    submissions: 4,
    views: 780,
    requirements: baseReq,
    tags: ["audi", "r8", "supercar"],
    imageUrl: "/cars/b4.jpg",
  },

  // ── Tier 3 · Super (2.5 + 3 + 3.5 + 4 = 13 SOL) ──
  {
    id: "t3-1",
    title: "Bugatti Chiron Super Sport — Monaco",
    description:
      "Chiron Super Sport spotted during Monaco GP weekend. Timestamp metadata required.",
    make: "Bugatti",
    model: "Chiron Super Sport",
    yearRange: "2020-2026",
    category: "hypercar",
    rarity: "legendary",
    tier: 3,
    reward: 2.5,
    location: "Monaco",
    radiusMiles: 5,
    status: "open",
    postedBy: "gp_spotter",
    postedByAvatar: "GP",
    postedAt: "2026-06-07T06:00:00Z",
    expiresAt: "2026-06-10T23:59:00Z",
    submissions: 8,
    views: 7100,
    requirements: { ...baseReq, mustBeMoving: true, mustIncludePlate: false },
    tags: ["bugatti", "chiron", "monaco"],
    imageUrl: "/cars/b8.jpg",
  },
  {
    id: "t3-2",
    title: "Aston Martin Valkyrie — London",
    description:
      "Road-legal Valkyrie in Greater London. Track-only variants do not qualify.",
    make: "Aston Martin",
    model: "Valkyrie",
    yearRange: "2022-2026",
    category: "hypercar",
    rarity: "unicorn",
    tier: 3,
    reward: 3,
    location: "London, UK",
    radiusMiles: 30,
    status: "open",
    postedBy: "british_motors",
    postedByAvatar: "BM",
    postedAt: "2026-06-03T12:00:00Z",
    expiresAt: "2026-07-03T23:59:00Z",
    submissions: 1,
    views: 9200,
    requirements: { ...baseReq, mustBeMoving: true, mustIncludePlate: false },
    tags: ["aston", "valkyrie", "london"],
    imageUrl: "/cars/b10.jpg",
  },
  {
    id: "t3-3",
    title: "Ferrari F40 — Texas",
    description:
      "F40 on public roads, not at a museum or static display. Any color accepted.",
    make: "Ferrari",
    model: "F40",
    yearRange: "1987-1992",
    category: "classic",
    rarity: "unicorn",
    tier: 3,
    reward: 3.5,
    location: "Texas, USA",
    radiusMiles: 500,
    status: "open",
    postedBy: "maranello_mad",
    postedByAvatar: "MM",
    postedAt: "2026-06-05T18:00:00Z",
    expiresAt: "2026-07-05T23:59:00Z",
    submissions: 1,
    views: 5620,
    requirements: {
      ...baseReq,
      minPhotos: 5,
      mustBeMoving: true,
      mustIncludePlate: false,
      notes: "Must be driving on public roads.",
    },
    tags: ["f40", "ferrari", "classic"],
    imageUrl: "/cars/b3.jpg",
  },
  {
    id: "t3-4",
    title: "Lamborghini Aventador SVJ — Dubai",
    description:
      "Aventador SVJ on public roads in Dubai or Abu Dhabi. ALA wing must be visible.",
    make: "Lamborghini",
    model: "Aventador SVJ",
    yearRange: "2019-2021",
    category: "supercar",
    rarity: "legendary",
    tier: 3,
    reward: 4,
    location: "Dubai, UAE",
    radiusMiles: 40,
    status: "open",
    postedBy: "gulf_spots",
    postedByAvatar: "GS",
    postedAt: "2026-06-04T08:00:00Z",
    expiresAt: "2026-07-04T23:59:00Z",
    submissions: 2,
    views: 3400,
    requirements: { ...baseReq, mustBeMoving: true },
    tags: ["lamborghini", "aventador", "svj"],
    imageUrl: "/cars/b5.jpg",
  },

  // ── Tier 4 · Hyper (5 + 6 + 8 + 10 = 29 SOL) ──
  {
    id: "t4-1",
    title: "McLaren F1 — Worldwide",
    description:
      "Verified McLaren F1 on public roads worldwide. Video + photos required.",
    make: "McLaren",
    model: "F1",
    yearRange: "1993-1998",
    category: "hypercar",
    rarity: "unicorn",
    tier: 4,
    reward: 5,
    location: "Worldwide",
    status: "open",
    postedBy: "apex_fund",
    postedByAvatar: "AF",
    postedAt: "2026-06-04T00:00:00Z",
    expiresAt: "2026-12-31T23:59:00Z",
    submissions: 0,
    views: 28400,
    featured: true,
    requirements: {
      minPhotos: 6,
      mustIncludePlate: false,
      mustIncludeLocation: true,
      mustBeMoving: true,
      notes: "Chassis number verification may be requested.",
    },
    tags: ["mclaren", "f1", "hypercar"],
    imageUrl: "/cars/b6.jpg",
  },
  {
    id: "t4-2",
    title: "Koenigsegg Jesko — Stockholm",
    description:
      "Jesko Attack or Absolut on Swedish public roads. Must show full body profile.",
    make: "Koenigsegg",
    model: "Jesko",
    yearRange: "2021-2026",
    category: "hypercar",
    rarity: "unicorn",
    tier: 4,
    reward: 6,
    location: "Stockholm, Sweden",
    radiusMiles: 50,
    status: "open",
    postedBy: "nordic_hunt",
    postedByAvatar: "NH",
    postedAt: "2026-06-02T10:00:00Z",
    expiresAt: "2026-08-02T23:59:00Z",
    submissions: 0,
    views: 12000,
    requirements: {
      ...baseReq,
      minPhotos: 5,
      mustBeMoving: true,
      mustIncludePlate: false,
    },
    tags: ["koenigsegg", "jesko", "hypercar"],
    imageUrl: "/cars/b8.jpg",
  },
  {
    id: "t4-3",
    title: "Ferrari LaFerrari — Milan",
    description:
      "LaFerrari coupe on public roads in Lombardy. No museum or dealer inventory.",
    make: "Ferrari",
    model: "LaFerrari",
    yearRange: "2013-2016",
    category: "hypercar",
    rarity: "unicorn",
    tier: 4,
    reward: 8,
    location: "Milan, Italy",
    radiusMiles: 35,
    status: "open",
    postedBy: "italia_exotics",
    postedByAvatar: "IE",
    postedAt: "2026-06-01T14:00:00Z",
    expiresAt: "2026-09-01T23:59:00Z",
    submissions: 0,
    views: 15600,
    requirements: {
      ...baseReq,
      minPhotos: 5,
      mustBeMoving: true,
      mustIncludePlate: false,
    },
    tags: ["ferrari", "laferrari", "hypercar"],
    imageUrl: "/cars/b1.jpg",
  },
  {
    id: "t4-4",
    title: "Bugatti Divo — Cannes",
    description:
      "Bugatti Divo on the French Riviera during summer season. Full car, clear lighting.",
    make: "Bugatti",
    model: "Divo",
    yearRange: "2019-2021",
    category: "hypercar",
    rarity: "unicorn",
    tier: 4,
    reward: 10,
    location: "Cannes, France",
    radiusMiles: 20,
    status: "open",
    postedBy: "riviera_hunt",
    postedByAvatar: "RH",
    postedAt: "2026-05-30T08:00:00Z",
    expiresAt: "2026-09-30T23:59:00Z",
    submissions: 0,
    views: 22000,
    requirements: {
      ...baseReq,
      minPhotos: 6,
      mustBeMoving: true,
      mustIncludePlate: false,
    },
    tags: ["bugatti", "divo", "hypercar"],
    imageUrl: "/cars/b8.jpg",
  },
];

export function getBountyById(id: string): Bounty | undefined {
  return bounties.find((b) => b.id === id);
}

export function formatSol(amount: number): string {
  const value = amount % 1 === 0 ? amount.toFixed(0) : amount.toFixed(2);
  return `${value} SOL`;
}

export function formatRelativeTime(dateStr: string): string {
  const date = new Date(dateStr);
  const now = new Date();
  const diffMs = now.getTime() - date.getTime();
  const diffHours = Math.floor(diffMs / (1000 * 60 * 60));
  const diffDays = Math.floor(diffHours / 24);

  if (diffHours < 1) return "Just now";
  if (diffHours < 24) return `${diffHours}h ago`;
  if (diffDays < 7) return `${diffDays}d ago`;
  return date.toLocaleDateString("en-US", { month: "short", day: "numeric" });
}

export function getTimeRemaining(expiresAt: string): string {
  const expiry = new Date(expiresAt);
  const now = new Date();
  const diffMs = expiry.getTime() - now.getTime();

  if (diffMs <= 0) return "Expired";

  const days = Math.floor(diffMs / (1000 * 60 * 60 * 24));
  const hours = Math.floor((diffMs % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));

  if (days > 0) return `${days}d ${hours}h left`;
  return `${hours}h left`;
}

export const categoryLabels: Record<string, string> = {
  exotic: "Exotic",
  classic: "Classic",
  jdm: "JDM",
  european: "European",
  muscle: "Muscle",
  supercar: "Supercar",
  hypercar: "Hypercar",
  prototype: "Prototype",
  "one-off": "One-Off",
};

export const statusConfig: Record<string, { label: string }> = {
  open: { label: "Open" },
  claimed: { label: "Claimed" },
  review: { label: "In review" },
  completed: { label: "Completed" },
  expired: { label: "Expired" },
};
